In [ ]:
import pandas as pd
import numpy as np

# Creating a DF

In [ ]:
# Make my own DF
import pandas as pd
import numpy as np

Name = ["Tom", "Jane", "Alice"]
Age = [20, 21, 19]
Major = ["Business", "Data Analytics", "Business"]

toDF = {"Name": Name, "Age": Age, "Major": Major}

DF = pd.DataFrame(toDF)

DF.head()


Name  Age           Major
0    Tom   20        Business
1   Jane   21  Data Analytics
2  Alice   19        Business

In [ ]:
# With Lists
import pandas as pd
import numpy as np

toDF2 = [["Tom", 20, "Business"], ["Jane", 21, "Data Analytics"], ["Alice", 19, "Business"]]

DF2 = pd.DataFrame(toDF2, columns = ["Name", "Age", "Major"])

DF.head()



Name  Age           Major
0    Tom   20        Business
1   Jane   21  Data Analytics
2  Alice   19        Business

In [ ]:
# From URL
import pandas as pd
import numpy as np

urlDF = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv"

DF3 = pd.read_csv(urlDF)

DF3.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
# From your Computer
import pandas as pd
import numpy as np

pathDF = "/Users/chelseaparlett/Desktop/Desktop/School/CPSC392parlettpelleriti/Data/penguins.csv"

DF4 = pd.read_csv(pathDF)

DF4.head()


# Exploring your DF

In [ ]:
# Checking out your DF

DF3.shape

# Python tells you the shape of your data (numbers of columns, etc.)


(53940, 10)

In [ ]:
# Column names

DF3.columns

# List of all of the column names


Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [ ]:
# What do your columns look like?

DF3.info()
DF3.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object 
 2   color    53940 non-null  object 
 3   clarity  53940 non-null  object 
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64  
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB


carat         depth  ...             y             z
count  53940.000000  53940.000000  ...  53940.000000  53940.000000
mean       0.797940     61.749405  ...      5.734526      3.538734
std        0.474011      1.432621  ...      1.142135      0.705699
min        0.200000     43.000000  ...      0.000000      0.000000
25%        0.400000     61.000000  ...      4.720000      2.910000
50%        0.700000     61.800000  ...      5.710000      3.530000
75%        1.040000     62.500000  ...      6.540000      4.040000
max        5.010000     79.000000  ...     58.900000     31.800000

[8 rows x 7 columns]

In [ ]:
# head, 12
# Argument for how many rows you want to see

DF3.head(12)

carat        cut color clarity  depth  table  price     x     y     z
0    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9    0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
10   0.30       Good     J     SI1   64.0   55.0    339  4.25  4.28  2.73
11   0.23      Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46

## groupby()

In [ ]:
# use groupby to get species average bill length
import pandas as pd
import numpy as np

urlDF1 = "https://raw.githubusercontent.com/cmparlettpelleriti/CPSC392ParlettPelleriti/master/Data/penguins.csv"
DF5 = pd.read_csv(urlDF1)

DF5.groupby(["species"])[["bill_length_mm", "bill_depth_mm"]].mean()

bill_length_mm  bill_depth_mm
species                                 
Adelie          38.791391      18.346358
Chinstrap       48.833824      18.420588
Gentoo          47.504878      14.982114

## Grabbing columns by name

Unnamed: 0            0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

## Dropping Missing Data

In [ ]:
# Check for missing values
DF5.isnull().sum()

# For each column, how many are missing?

Unnamed: 0            0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [ ]:
# Dropping all of missing data to only have rows complete info

DF5 = DF5.dropna()
# checking
DF5.isnull().sum()


Unnamed: 0           0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

In [ ]:
# another way to drop your data

DF5.dropna(inplace = True)
DF5.reset_index(inplace = True)

## Creating Dummy Variables
### A single dummy variable

In [ ]:
# simulate data
np.random.seed(8675309)

n = 100
x1 = np.random.choice(["A", "B", "C"], n)
x2 = np.random.normal(0,1,n)

df = pd.DataFrame({"group":x1, "happiness": x2})

df.head()

group  happiness
0     B  -0.998062
1     A   1.152839
2     A   0.193641
3     A   0.356045
4     A  -1.046417

In [ ]:
# notice that the categorical variable `group`, has more than 2 categories.
dummies = pd.get_dummies(df, columns = ["group"])

# many algorithms want dummy/binary variables, so let's turn `group` into dummy/binary variables!

# you can see that we now have 3 columns, A, B, and C that
# are all binary variables indicating whether each person was
# A (1-yes, 0-no), B (1-yes, 0-no), or C (1-yes, 0-no)
dummies


happiness  group_A  group_B  group_C
0   -0.998062        0        1        0
1    1.152839        1        0        0
2    0.193641        1        0        0
3    0.356045        1        0        0
4   -1.046417        1        0        0
..        ...      ...      ...      ...
95   0.251880        0        1        0
96  -0.940828        0        0        1
97   1.012550        0        1        0
98   0.778642        0        1        0
99  -2.165909        1        0        0

[100 rows x 4 columns]

### Multiple dummy variables

In [ ]:
np.random.seed(8675309)

n = 100
letter_grade = np.random.choice(["A", "B", "C", "D", "F"], n)
class_level = np.random.choice(["Freshman", "Sophomore", "Junior", "Senior"], n)
x2 = np.random.normal(0,1,n)

df = pd.DataFrame({"Grade":letter_grade, "Class": class_level, "happiness": x2})

df.head()

Grade      Class  happiness
0     B  Sophomore   0.629483
1     F   Freshman   2.109350
2     F   Freshman  -1.292751
3     A  Sophomore  -0.020285
4     A     Senior   0.735859

In [ ]:
df = pd.get_dummies(df, columns = ["Grade", "Class"])

df.head()

happiness  Grade_A  Grade_B  ...  Class_Junior  Class_Senior  Class_Sophomore
0   0.629483        0        1  ...             0             0                1
1   2.109350        0        0  ...             0             0                0
2  -1.292751        0        0  ...             0             0                0
3  -0.020285        1        0  ...             0             0                1
4   0.735859        1        0  ...             0             1                0

[5 rows x 10 columns]

# Grabbing Subsets of Data

## By Column Name

In [ ]:
# Pulling certain rows/columns/sets

DF5["species"]

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...    
328    Chinstrap
329    Chinstrap
330    Chinstrap
331    Chinstrap
332    Chinstrap
Name: species, Length: 333, dtype: object

In [ ]:
DF5["bill_length_mm"].mean()

43.99279279279281

## By Index

In [ ]:
DF5.iloc[8]

index                       13
Unnamed: 0                  13
species                 Adelie
island               Torgersen
bill_length_mm            38.6
bill_depth_mm             21.2
flipper_length_mm        191.0
body_mass_g             3800.0
sex                       male
year                      2007
Name: 8, dtype: object

In [ ]:
#9th row
DF5.iloc[[8]]

index  Unnamed: 0 species  ... body_mass_g   sex  year
8     13          13  Adelie  ...      3800.0  male  2007

[1 rows x 10 columns]

In [ ]:
#3-7 row
DF5.iloc[2:7]

index  Unnamed: 0 species  ... body_mass_g     sex  year
2      2           2  Adelie  ...      3250.0  female  2007
3      4           4  Adelie  ...      3450.0  female  2007
4      5           5  Adelie  ...      3650.0    male  2007
5      6           6  Adelie  ...      3625.0  female  2007
6      7           7  Adelie  ...      4675.0    male  2007

[5 rows x 10 columns]

In [ ]:
DF5.iloc[2:7, 2:4]
# DF5.iloc[rows, columns]

species     island
2  Adelie  Torgersen
3  Adelie  Torgersen
4  Adelie  Torgersen
5  Adelie  Torgersen
6  Adelie  Torgersen

In [ ]:
DF5.iloc[10:21, 4:7]

bill_length_mm  bill_depth_mm  flipper_length_mm
10            36.6           17.8              185.0
11            38.7           19.0              195.0
12            42.5           20.7              197.0
13            34.4           18.4              184.0
14            46.0           21.5              194.0
15            37.8           18.3              174.0
16            37.7           18.7              180.0
17            35.9           19.2              189.0
18            38.2           18.1              185.0
19            38.8           17.2              180.0
20            35.3           18.9              187.0

## By Condition (Booleans)

In [ ]:
# Torgersen Penguins
torg = DF5["island"] == "Torgersen"

DF5.loc[torg].head()

index  Unnamed: 0 species  ... body_mass_g     sex  year
0      0           0  Adelie  ...      3750.0    male  2007
1      1           1  Adelie  ...      3800.0  female  2007
2      2           2  Adelie  ...      3250.0  female  2007
3      4           4  Adelie  ...      3450.0  female  2007
4      5           5  Adelie  ...      3650.0    male  2007

[5 rows x 10 columns]

In [ ]:
# bill length less than 39
shortboi = DF5["bill_length_mm"] < 39

DF5.loc[shortboi].head()

index  Unnamed: 0 species  ... body_mass_g     sex  year
3       4           4  Adelie  ...      3450.0  female  2007
5       6           6  Adelie  ...      3625.0  female  2007
8      13          13  Adelie  ...      3800.0    male  2007
9      14          14  Adelie  ...      4400.0    male  2007
10     15          15  Adelie  ...      3700.0  female  2007

[5 rows x 10 columns]

In [ ]:
# bill length less than 39 and bill depth less than 18
shortboi2 = (DF5["bill_length_mm"] < 39) & (DF5["bill_depth_mm"] < 18)

DF5.loc[shortboi2].head()

index  Unnamed: 0 species  ... body_mass_g     sex  year
5       6           6  Adelie  ...      3625.0  female  2007
10     15          15  Adelie  ...      3700.0  female  2007
19     24          24  Adelie  ...      3800.0    male  2007
29     34          34  Adelie  ...      3325.0  female  2007
39     44          44  Adelie  ...      3000.0  female  2007

[5 rows x 10 columns]

In [ ]:
# mean body mass of short bois
DF5.loc[shortboi2, "body_mass_g"].mean()

3326.315789473684

In [ ]:
# bill length less than 39 OR bill depth less than 18
shortboi3 = (DF5["bill_length_mm"] < 39) | (DF5["bill_depth_mm"] < 18)

DF5.loc[shortboi3].head()

index  Unnamed: 0 species  ... body_mass_g     sex  year
1      1           1  Adelie  ...      3800.0  female  2007
3      4           4  Adelie  ...      3450.0  female  2007
5      6           6  Adelie  ...      3625.0  female  2007
7     12          12  Adelie  ...      3200.0  female  2007
8     13          13  Adelie  ...      3800.0    male  2007

[5 rows x 10 columns]

### By Column Type

In [ ]:
#info
DF5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   index              333 non-null    int64  
 1   Unnamed: 0         333 non-null    int64  
 2   species            333 non-null    object 
 3   island             333 non-null    object 
 4   bill_length_mm     333 non-null    float64
 5   bill_depth_mm      333 non-null    float64
 6   flipper_length_mm  333 non-null    float64
 7   body_mass_g        333 non-null    float64
 8   sex                333 non-null    object 
 9   year               333 non-null    int64  
dtypes: float64(4), int64(3), object(3)
memory usage: 26.1+ KB


In [ ]:
num = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

DF5_numeric = DF5.select_dtypes(include = num)

DF5_numeric.head()



index  Unnamed: 0  bill_length_mm  ...  flipper_length_mm  body_mass_g  year
0      0           0            39.1  ...              181.0       3750.0  2007
1      1           1            39.5  ...              186.0       3800.0  2007
2      2           2            40.3  ...              195.0       3250.0  2007
3      4           4            36.7  ...              193.0       3450.0  2007
4      5           5            39.3  ...              190.0       3650.0  2007

[5 rows x 7 columns]

In [ ]:
bill_vars = [columnname for columnname in DF5.columns if columnname.startswith("bill")]

DF5[bill_vars]

bill_length_mm  bill_depth_mm
0              39.1           18.7
1              39.5           17.4
2              40.3           18.0
3              36.7           19.3
4              39.3           20.6
..              ...            ...
328            55.8           19.8
329            43.5           18.1
330            49.6           18.2
331            50.8           19.0
332            50.2           18.7

[333 rows x 2 columns]

# Adding Data to a Data Frame

In [ ]:
# bill ratio

DF5["bill_Ratio"] = DF5["bill_length_mm"]/DF5["bill_depth_mm"]

In [ ]:
DF5.head()

index  Unnamed: 0 species     island  ...  body_mass_g     sex  year  bill_Ratio
0      0           0  Adelie  Torgersen  ...       3750.0    male  2007    2.090909
1      1           1  Adelie  Torgersen  ...       3800.0  female  2007    2.270115
2      2           2  Adelie  Torgersen  ...       3250.0  female  2007    2.238889
3      4           4  Adelie  Torgersen  ...       3450.0  female  2007    1.901554
4      5           5  Adelie  Torgersen  ...       3650.0    male  2007    1.907767

[5 rows x 11 columns]

# Numpy Array Operations

In [ ]:
# creating 
x = np.array([1,2,3,4,5,6])

x_list = [1,2,3,4,5,6]

In [ ]:
# indexing
x_list[2]

x[2]

3

In [ ]:
# multiplication
x_list * 3

x * 3


array([ 3,  6,  9, 12, 15, 18])

In [ ]:
y = np.array([2,2,2,2,2,2])
y_list = [2,2,2,2,2,2]

In [ ]:
# addition

x_list + y_list

x + y

array([3, 4, 5, 6, 7, 8])

## Using `np` to calculate distance

$ dist = \sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2 + ... + (x_n - y_n)^2}$

In [ ]:
# distances
x - y

array([-1,  0,  1,  2,  3,  4])

In [ ]:
(x-y)**2

array([ 1,  0,  1,  4,  9, 16])

In [ ]:
np.sum((x-y)**2)

31

In [ ]:
np.sqrt(np.sum((x-y)**2))

5.5677643628300215

In [ ]:
# the norm way
np.linalg.norm(x-y)

5.5677643628300215

## Random Numbers

In [ ]:
# normal

np.random.normal(loc = 0, scale = 1, size = 10)

array([ 1.25664584,  1.60299628, -0.02572116,  0.49999157,  1.28782204,
        0.23522165, -0.72680735, -3.02387235,  0.71492412, -1.26904115])

In [ ]:
# uniform

np.random.uniform(low = 0, high = 1, size = 10)

array([0.45400834, 0.73640482, 0.7127012 , 0.47904714, 0.93373901,
       0.44879873, 0.88103047, 0.77162477, 0.10020401, 0.58178108])

In [ ]:
# choice
names = ["Chelsea", "Tony", "Julie", "Chris", "Quinn"]

np.random.choice(names)

'Julie'

In [ ]:
# choice with replacement

np.random.choice(["A", "B"], size = 100, replace = True)


array(['B', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'B', 'A', 'A', 'A',
       'A', 'B', 'B', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'A', 'A', 'B',
       'B', 'A', 'B', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'B',
       'B', 'A', 'B', 'B', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'A',
       'B', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'A', 'A', 'B', 'A', 'B',
       'A', 'A', 'A', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B',
       'B', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'A', 'B', 'B', 'B', 'A',
       'A', 'A', 'A', 'B', 'A', 'A', 'B', 'B', 'B'], dtype='<U1')

In [ ]:
# seed

np.random.seed(42069)
np.random.normal(0,1,1)


array([-0.07446903])